{"name": "Проверка возврата ошибки если передать неверный id заказа или курьера", "status": "passed", "description": "Выполняем PUT запрос /api/v1/orders/accept/ с указанием неверного id заказа в качестве path параметра или неверного id курьера в качестве query параметра. Предварительно создаем заказ и курьера", "parameters": [{"name": "incorrect_id_object", "value": "'order'"}, {"name": "message", "value": "'Заказа с таким id не существует'"}], "start": 1746475658308, "stop": 1746475658817, "uuid": "8220cbbe-217b-4037-a50a-5cbb9b22e4da", "historyId": "be98e7e91bd42a04af0125647472ff11", "testCaseId": "84000f71cd9bf8f979f3fccdb6454b0e", "fullName": "tests.test_accept_order.TestAcceptOrder#test_accept_order_with_incorect_id_status_code_is_not_found", "labels": [{"name": "parentSuite", "value": "Тестирование API сервиса заказа самоката"}, {"name": "suite", "value": "Тестирование принятия заказа"}, {"name": "subSuite", "value": "Тестирование возврата ошибки при некорректном принятия заказа"}, {"name": "host", "value": "desktop"}, {"name": "thread", "value": "361687-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_accept_order"}]}